SET NAMES WIN1251;

SET SQL DIALECT 3;

CONNECT 'localhost:C:\Work\Analit\VSS\Inforoom\Delphi\AnalitF R 4.2.151.470\src\bin\ANALITF.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

SET AUTODDL ON;

ALTER TABLE PARAMS ADD PRINTORDERSAFTERSEND FB_BOOLEAN;

