SET NAMES WIN1251;

SET SQL DIALECT 3;

CONNECT 'C:\Work\Analit\VSS\Inforoom\Delphi\AnalitF R 4.2.151.470\src\bin\ANALITF.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

SET AUTODDL ON;

ALTER TABLE PARAMS ADD USEOSOPENWAYBILL FB_BOOLEAN DEFAULT 0;

ALTER TABLE PARAMS ADD USEOSOPENREJECT FB_BOOLEAN DEFAULT 1;

/* Drop table-fields... */
ALTER TABLE PARAMS DROP USENTLM;

ALTER TABLE PARAMS DROP USEOSOPEN;

