DROP TABLE IF EXISTS DEPT;
DROP TABLE IF EXISTS EMP;
DROP TABLE IF EXISTS MYDAC_Loaded;
DROP TABLE IF EXISTS CRGRID_TEST;
DROP TABLE IF EXISTS MYDAC_Pictures;
DROP TABLE IF EXISTS MYDAC_Text;
DROP TABLE IF EXISTS EMP_TRANACTION_SAFE;
/*!50001
DROP PROCEDURE IF EXISTS sel_from_emp
*/;