{*************************************************}
{                                                 }
{             FIBPlus Script, version 1.9         }
{                                                 }
{     Copyright by Nikolay Trifonov, 2003-2007    }
{                                                 }
{           E-mail: t_nick@mail.ru                }
{                                                 }
{*************************************************}

//{$DEFINE FIBPLUS_SCRIPT_TRIAL}
