ALTER TABLE PARAMS ADD USEOSOPENWAYBILL FB_BOOLEAN DEFAULT 0;

ALTER TABLE PARAMS ADD USEOSOPENREJECT FB_BOOLEAN DEFAULT 1;

/* Drop table-fields... */
ALTER TABLE PARAMS DROP USENTLM;

ALTER TABLE PARAMS DROP USEOSOPEN;

update PROVIDER set mdbversion = 42 where id = 0;

commit work;