mysql_num_fields
mysql_fetch_field_direct
mysql_field_count
mysql_affected_rows
mysql_insert_id
mysql_errno
mysql_error
mysql_info
mysql_thread_id
mysql_character_set_name
mysql_init
mysql_ssl_set
mysql_real_connect
mysql_close
mysql_select_db
mysql_real_query
mysql_kill
mysql_ping
mysql_get_server_info
mysql_get_client_info
mysql_get_host_info
mysql_use_result
mysql_options
mysql_free_result
mysql_fetch_row
mysql_fetch_lengths
mysql_server_init
mysql_server_end
mysql_stmt_init
mysql_stmt_prepare
mysql_stmt_execute
mysql_stmt_param_count
mysql_stmt_bind_param
mysql_stmt_bind_result
mysql_stmt_field_count
mysql_stmt_close
mysql_stmt_free_result
mysql_stmt_errno
mysql_stmt_error
mysql_stmt_fetch
mysql_stmt_fetch_column
mysql_stmt_send_long_data
mysql_stmt_prepare_result
mysql_stmt_result_metadata
mysql_stmt_param_metadata
mysql_stmt_affected_rows
mysql_stmt_store_result
mysql_more_results
mysql_next_result
