SET NAMES WIN1251;

SET SQL DIALECT 3;

CONNECT 'C:\Work\Analit\VSS\Inforoom\Delphi\AnalitF\src\bin\ANALITF.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

SET AUTODDL ON;

ALTER TABLE PARAMS ADD USENTLM FB_BOOLEAN DEFAULT 1;

ALTER TABLE PARAMS ALTER COLUMN ID POSITION 1;

ALTER TABLE PARAMS ALTER COLUMN CLIENTID POSITION 2;

ALTER TABLE PARAMS ALTER COLUMN RASCONNECT POSITION 3;

ALTER TABLE PARAMS ALTER COLUMN RASENTRY POSITION 4;

ALTER TABLE PARAMS ALTER COLUMN RASNAME POSITION 5;

ALTER TABLE PARAMS ALTER COLUMN RASPASS POSITION 6;

ALTER TABLE PARAMS ALTER COLUMN CONNECTCOUNT POSITION 7;

ALTER TABLE PARAMS ALTER COLUMN CONNECTPAUSE POSITION 8;

ALTER TABLE PARAMS ALTER COLUMN PROXYCONNECT POSITION 9;

ALTER TABLE PARAMS ALTER COLUMN PROXYNAME POSITION 10;

ALTER TABLE PARAMS ALTER COLUMN PROXYPORT POSITION 11;

ALTER TABLE PARAMS ALTER COLUMN PROXYUSER POSITION 12;

ALTER TABLE PARAMS ALTER COLUMN PROXYPASS POSITION 13;

ALTER TABLE PARAMS ALTER COLUMN SERVICENAME POSITION 14;

ALTER TABLE PARAMS ALTER COLUMN HTTPHOST POSITION 15;

ALTER TABLE PARAMS ALTER COLUMN HTTPPORT POSITION 16;

ALTER TABLE PARAMS ALTER COLUMN HTTPNAME POSITION 17;

ALTER TABLE PARAMS ALTER COLUMN HTTPPASS POSITION 18;

ALTER TABLE PARAMS ALTER COLUMN UPDATEDATETIME POSITION 19;

ALTER TABLE PARAMS ALTER COLUMN LASTDATETIME POSITION 20;

ALTER TABLE PARAMS ALTER COLUMN FASTPRINT POSITION 21;

ALTER TABLE PARAMS ALTER COLUMN SHOWREGISTER POSITION 22;

ALTER TABLE PARAMS ALTER COLUMN NEWWARES POSITION 23;

ALTER TABLE PARAMS ALTER COLUMN USEFORMS POSITION 24;

ALTER TABLE PARAMS ALTER COLUMN OPERATEFORMS POSITION 25;

ALTER TABLE PARAMS ALTER COLUMN OPERATEFORMSSET POSITION 26;

ALTER TABLE PARAMS ALTER COLUMN AUTOPRINT POSITION 27;

ALTER TABLE PARAMS ALTER COLUMN STARTPAGE POSITION 28;

ALTER TABLE PARAMS ALTER COLUMN LASTCOMPACT POSITION 29;

ALTER TABLE PARAMS ALTER COLUMN CUMULATIVE POSITION 30;

ALTER TABLE PARAMS ALTER COLUMN STARTED POSITION 31;

ALTER TABLE PARAMS ALTER COLUMN EXTERNALORDERSEXE POSITION 32;

ALTER TABLE PARAMS ALTER COLUMN EXTERNALORDERSPATH POSITION 33;

ALTER TABLE PARAMS ALTER COLUMN EXTERNALORDERSCREATE POSITION 34;

ALTER TABLE PARAMS ALTER COLUMN RASSLEEP POSITION 35;

ALTER TABLE PARAMS ALTER COLUMN HTTPNAMECHANGED POSITION 36;

ALTER TABLE PARAMS ALTER COLUMN SHOWALLCATALOG POSITION 37;

ALTER TABLE PARAMS ALTER COLUMN CDS POSITION 38;

ALTER TABLE PARAMS ALTER COLUMN ORDERSHISTORYDAYCOUNT POSITION 39;

ALTER TABLE PARAMS ALTER COLUMN CONFIRMDELETEOLDORDERS POSITION 40;

ALTER TABLE PARAMS ALTER COLUMN USENTLM POSITION 41;

